### ISSUE TITLE
Error when copying text which contains backticks.

### ISSUE THREAD

**Issue by oct4vian** [iamskok/gatsby-remark-code-buttons#2]
I have this code snippet which I want to copy:

```javascript
import styles from './Header.module.scss';
import logo from '../images/logo.svg';

const Header = () => {
  return (
    <header className={`${styles.header} color-white px-24px flex`}>
      <div className={styles.logo}>
        <img src={logo} alt="WFinance" />
        <span className="ml-8px pt-8px">Developer Portal</span>
      </div>

      <TopNav />

      <SearchBox />
    </header>
  );
};
```

When I try to use the copy button, I get the error
**Uncaught ReferenceError: styles is not defined
    at HTMLDivElement.onclick ((index):6)**

The problem is that chrome sees the styles as a variable and thinks that it is undefined. Here is a picture of what displays if I click to see the code.

![image (1)](https://user-images.githubusercontent.com/17726663/60020290-6b3f0b80-9698-11e9-9848-0805cbd9a8e5.png)

The styles.code should be orange colored (string), but it is seen as a variable.

The fix should be escaping the dollar sign and the curly braces.
I could open a Pull Request and fix it.

Thank you.

**Comment by iamskok** [comment]
@oct4vian I’m very sorry for getting back to you so late. You are more than welcome to submit a PR! Feel free to reopen this issue once you are ready.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
