### ISSUE TITLE
Keep proper format during code chunk copy

### ISSUE THREAD

**Issue by Blackglade** [iamskok/gatsby-remark-code-buttons#3]
I notice when copying code that line breaks are essentially removed and all the code that is copied is copied unto a single line. Would there be any way keep the proper format during the code chunk copy?

**Comment by iamskok** [comment]
@Blackglade would you be interested in submitting a PR? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Blackglade** [comment]
Yes I would! I'll look into it when I get more time and submit a PR

**Comment by iamskok** [comment]
Sounds good! Feel free to reopen this issue
